spring:
  h2:
    console:
      enabled: true
      path: /h2
      
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:swdroid
    username: swdroid
    password:
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
        ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        
server:
  port: 8080        